# Generated by Django 5.2 on 2025-09-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('underprocess', 'Underprocess'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
