# Generated by Django 5.2 on 2025-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/'),
        ),
    ]
