# Generated by Django 5.2 on 2025-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker')], default='worker', max_length=20),
        ),
    ]
