# Generated by Django 5.2 on 2025-09-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='worker_type',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('painter', 'Painter'), ('electrician', 'Electrician'), ('fabricator', 'Fabricator'), ('welder', 'Welder'), ('carpenter', 'Carpenter')], default='plumber', max_length=50),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='workers.skillcategory'),
        ),
    ]
