# Generated by Django 5.2 on 2025-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workerprofile_worker_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='worker_profiles/'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
